# ═══════════════════════════════════════════════════════════
#  PROMPTAHOLICS — Weekly Image Generator Workflow
#  Runs every Monday at 9:00 AM ET automatically
#  Also runnable manually from GitHub Actions tab
# ═══════════════════════════════════════════════════════════

name: Weekly Image Generator 🎨

on:
  # ── Auto-run every Monday at 9am ET (14:00 UTC) ──
  schedule:
    - cron: '0 14 * * 1'

  # ── Also allow manual trigger from GitHub Actions tab ──
  workflow_dispatch:
    inputs:
      reason:
        description: 'Why are you running this manually?'
        required: false
        default: 'Manual refresh'

jobs:
  generate-images:
    name: Generate Weekly Images
    runs-on: ubuntu-latest

    permissions:
      contents: write   # Needed to commit and push images

    steps:

      # ── 1: Check out the repo ──
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # ── 2: Set up Node.js ──
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ── 3: Run the image generator ──
      - name: Generate images via DALL·E 3
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🎨 Starting Promptaholics Weekly Image Generator"
          echo "📅 Date: $(date)"
          node generate-images.js

      # ── 4: Check if new images were created ──
      - name: Check for new images
        id: check-images
        run: |
          if [ -d "images" ] && [ "$(ls -A images/*.jpg 2>/dev/null)" ]; then
            echo "images_exist=true" >> $GITHUB_OUTPUT
            echo "✅ Images found:"
            ls -lh images/*.jpg
          else
            echo "images_exist=false" >> $GITHUB_OUTPUT
            echo "⚠️ No images found"
          fi

      # ── 5: Commit and push images to repo ──
      - name: Commit and push new images
        if: steps.check-images.outputs.images_exist == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Promptaholics Bot 🤖"

          git add images/
          git status

          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "ℹ️ No changes to commit — images are identical to last week"
          else
            WEEK=$(date +"%Y-W%V")
            git commit -m "🎨 Weekly image refresh — $WEEK

          Generated by DALL·E 3 via GitHub Actions
          Prompts: Golden Hour Portrait, AI Action Figure Box, Urban Street Photography, The Character Forge
          Quality: HD | Cost: ~\$0.32"

            git push
            echo "✅ Images committed and pushed — Netlify will deploy automatically"
          fi

      # ── 6: Report status ──
      - name: Report completion
        if: always()
        run: |
          echo "════════════════════════════════════"
          echo "  Promptaholics Image Generator Done"
          echo "════════════════════════════════════"
          echo "Run time: $(date)"
          echo "Trigger: ${{ github.event_name }}"
          if [ "${{ steps.check-images.outputs.images_exist }}" == "true" ]; then
            echo "Status: ✅ SUCCESS — New images deployed"
          else
            echo "Status: ❌ FAILED — Check logs above"
          fi
