// netlify/edge-functions/vault-image.js
// Handles both /share/vault and /share/prompt routes

export default async (request, context) => {
  const url = new URL(request.url);
  const id  = url.searchParams.get('id') || '';
  const path = url.pathname;

  // ── Prompt Share ──────────────────────────────────────────────
  if(path === '/share/prompt') {
    let name = 'AI Prompt — Promptaholics';
    let text = 'A free AI prompt generated by Promptaholics PA Agent.';

    if(id) {
      try {
        const fbUrl = `https://firestore.googleapis.com/v1/projects/promptaholics-534d3/databases/(default)/documents/prompt-shares/${id}`;
        const res = await fetch(fbUrl);
        if(res.ok) {
          const data = await res.json();
          if(data.fields) {
            name = (data.fields.name?.stringValue || 'AI Prompt') + ' — Promptaholics';
            text = (data.fields.text?.stringValue || text).slice(0, 160);
          }
        }
      } catch(e) {}
    }

    const esc = (s) => String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
    const ogImg = 'https://promptaholics.com/og-default.png';

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${esc(name)}</title>
<meta name="description" content="${esc(text)}"/>
<meta property="og:type" content="website"/>
<meta property="og:site_name" content="Promptaholics"/>
<meta property="og:title" content="${esc(name)}"/>
<meta property="og:description" content="${esc(text)}"/>
<meta property="og:image" content="${esc(ogImg)}"/>
<meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>
<meta property="og:url" content="${esc(url.href)}"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content="${esc(name)}"/>
<meta name="twitter:description" content="${esc(text)}"/>
<meta name="twitter:image" content="${esc(ogImg)}"/>
<style>body{margin:0;background:#07070a;display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:sans-serif;color:rgba(240,240,248,.5);font-size:13px;}</style>
</head>
<body>
<div>Loading...</div>
<script>window.location.replace('/prompt-share.html?id=' + encodeURIComponent('${id}'));</script>
</body>
</html>`;

    return new Response(html, {
      status: 200,
      headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'public, max-age=3600' }
    });
  }

  // ── Vault Image Share ─────────────────────────────────────────
  var title  = 'AI Art — Promptaholics';
  var desc   = 'AI-generated artwork. Create your own free at Promptaholics!';
  var imgUrl = '';

  if(id) {
    try {
      const fbUrl = `https://firestore.googleapis.com/v1/projects/promptaholics-534d3/databases/(default)/documents/vault-shares/${id}`;
      const res = await fetch(fbUrl);
      if(res.ok) {
        const data = await res.json();
        if(data.fields) {
          imgUrl = data.fields.imageUrl?.stringValue || '';
          title  = (data.fields.title?.stringValue  || 'AI Art') + ' — Promptaholics';
          desc   = (data.fields.prompt?.stringValue || desc).slice(0, 160);
        }
      }
    } catch(e) {}
  }

  let ogImg = 'https://promptaholics.com/og-default.png';
  if(imgUrl && imgUrl.includes('res.cloudinary.com')) {
    ogImg = imgUrl.replace('/upload/', '/upload/w_1200,h_630,c_fill,g_center/');
  } else if(imgUrl) {
    ogImg = imgUrl;
  }

  const esc = (s) => String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${esc(title)}</title>
<meta name="description" content="${esc(desc)}"/>
<meta property="og:type" content="website"/>
<meta property="og:site_name" content="Promptaholics"/>
<meta property="og:title" content="${esc(title)}"/>
<meta property="og:description" content="${esc(desc)}"/>
<meta property="og:image" content="${esc(ogImg)}"/>
<meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>
<meta property="og:url" content="${esc(url.href)}"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:title" content="${esc(title)}"/>
<meta name="twitter:description" content="${esc(desc)}"/>
<meta name="twitter:image" content="${esc(ogImg)}"/>
<style>body{margin:0;background:#07070a;display:flex;align-items:center;justify-content:center;min-height:100vh;font-family:sans-serif;color:rgba(240,240,248,.5);font-size:13px;}</style>
</head>
<body>
<div>Loading...</div>
<script>window.location.replace('/vault-image.html?id=' + encodeURIComponent('${id}'));</script>
</body>
</html>`;

  return new Response(html, {
    status: 200,
    headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'public, max-age=3600' }
  });
};

export const config = { path: ['/share/vault', '/share/prompt'] };
